### ISSUE TITLE
Uninitialized-use warning with CAF 18.3

### ISSUE THREAD

**Issue by ckreibich** [actor-framework/actor-framework#1280]
I started seeing these with GCC 11.1.1 (Fedora 34), via Zeek's Broker project:
```
In file included from /home/christian/devel/zeek/zeek/auxil/broker/caf/libcaf_core/caf/make_config_option.hpp:10,
                 from /home/christian/devel/zeek/zeek/auxil/broker/caf/libcaf_core/caf/config_option_set.hpp:16,
                 from /home/christian/devel/zeek/zeek/auxil/broker/caf/libcaf_core/caf/detail/config_consumer.hpp:9,
                 from /home/christian/devel/zeek/zeek/auxil/broker/caf/libcaf_core/src/detail/parse.cpp:7:
In constructor ‘caf::config_value::config_value(T&&) [with T = long int&; E = void]’,
    inlined from ‘caf::pec caf::detail::config_consumer::value(T&&) [with T = long int&]’ at /home/christian/devel/zeek/zeek/auxil/broker/caf/libcaf_core/caf/detail/config_consumer.hpp:105:22,
    inlined from ‘void caf::detail::parser::read_number_or_timespan(State&, Consumer&, EnableRange)::interim_consumer::value(int64_t) [with State = caf::parser_state<const char*>; Consumer = caf::detail::config_consumer; EnableRange = std::integral_constant<bool, false>]’ at /home/christian/devel/zeek/zeek/auxil/broker/caf/libcaf_core/caf/detail/parser/read_number_or_timespan.hpp:46:23,
    inlined from ‘caf::detail::parser::read_number<caf::parser_state<const char*>, caf::detail::parser::read_number_or_timespan<caf::parser_state<const char*>, caf::detail::config_consumer, std::integral_constant<bool, false> >(caf::parser_state<const char*>&, caf::detail::config_consumer&, std::integral_constant<bool, false>)::interim_consumer, std::integral_constant<bool, true>, std::integral_constant<bool, false> >(caf::parser_state<const char*>&, caf::detail::parser::read_number_or_timespan<caf::parser_state<const char*>, caf::detail::config_consumer, std::integral_constant<bool, false> >(caf::parser_state<const char*>&, caf::detail::config_consumer&, std::integral_constant<bool, false>)::interim_consumer&, std::integral_constant<bool, true>, std::integral_constant<bool, false>)::<lambda()>’ at /home/christian/devel/zeek/zeek/auxil/broker/caf/libcaf_core/caf/detail/parser/read_number.hpp:51:21,
    inlined from ‘caf::detail::parser::read_number<caf::parser_state<const char*>, caf::detail::parser::read_number_or_timespan<caf::parser_state<const char*>, caf::detail::config_consumer, std::integral_constant<bool, false> >(caf::parser_state<const char*>&, caf::detail::config_consumer&, std::integral_constant<bool, false>)::interim_consumer, std::integral_constant<bool, true>, std::integral_constant<bool, false> >(caf::parser_state<const char*>&, caf::detail::parser::read_number_or_timespan<caf::parser_state<const char*>, caf::detail::config_consumer, std::integral_constant<bool, false> >(caf::parser_state<const char*>&, caf::detail::config_consumer&, std::integral_constant<bool, false>)::interim_consumer&, std::integral_constant<bool, true>, std::integral_constant<bool, false>)::<lambda()>’ at /home/christian/devel/zeek/zeek/auxil/broker/caf/libcaf_core/caf/detail/parser/read_number.hpp:49:42,
    inlined from ‘caf::detail::scope_guard<Fun>::~scope_guard() [with Fun = caf::detail::parser::read_number<caf::parser_state<const char*>, caf::detail::parser::read_number_or_timespan<caf::parser_state<const char*>, caf::detail::config_consumer, std::integral_constant<bool, false> >(caf::parser_state<const char*>&, caf::detail::config_consumer&, std::integral_constant<bool, false>)::interim_consumer, std::integral_constant<bool, true>, std::integral_constant<bool, false> >(caf::parser_state<const char*>&, caf::detail::parser::read_number_or_timespan<caf::parser_state<const char*>, caf::detail::config_consumer, std::integral_constant<bool, false> >(caf::parser_state<const char*>&, caf::detail::config_consumer&, std::integral_constant<bool, false>)::interim_consumer&, std::integral_constant<bool, true>, std::integral_constant<bool, false>)::<lambda()>]’ at /home/christian/devel/zeek/zeek/auxil/broker/caf/libcaf_core/caf/detail/scope_guard.hpp:29:11,
    inlined from ‘void caf::detail::parser::read_number(State&, Consumer&, EnableFloat, EnableRange) [with State = caf::parser_state<const char*>; Consumer = caf::detail::parser::read_number_or_timespan<caf::parser_state<const char*>, caf::detail::config_consumer, std::integral_constant<bool, false> >(caf::parser_state<const char*>&, caf::detail::config_consumer&, std::integral_constant<bool, false>)::interim_consumer; EnableFloat = std::integral_constant<bool, true>; EnableRange = std::integral_constant<bool, false>]’ at /home/christian/devel/zeek/zeek/auxil/broker/caf/libcaf_core/caf/detail/parser/read_number.hpp:178:1,
    inlined from ‘void caf::detail::parser::read_number_or_timespan(State&, Consumer&, EnableRange) [with State = caf::parser_state<const char*>; Consumer = caf::detail::config_consumer; EnableRange = std::integral_constant<bool, false>]’ at /home/christian/devel/zeek/zeek/auxil/broker/caf/libcaf_core/caf/detail/parser/read_number_or_timespan.hpp:74:5,
    inlined from ‘void caf::detail::parser::read_config_value(State&, Consumer&&, InsideList) [with State = caf::parser_state<const char*>; Consumer = caf::detail::config_consumer&; InsideList = std::integral_constant<bool, false>]’ at /home/christian/devel/zeek/zeek/auxil/broker/caf/libcaf_core/caf/detail/parser/read_config.hpp:228:5:
/home/christian/devel/zeek/zeek/auxil/broker/caf/libcaf_core/caf/config_value.hpp:106:8: warning: ‘*(long int*)((char*)&ic + offsetof(caf::detail::parser::read_number_or_timespan::interim_consumer, caf::detail::parser::read_number_or_timespan::interim_consumer::interim.caf::variant<caf::none_t, long int, double>::data_.caf::detail::variant_data<caf::none_t, long int, double, caf::unit_t, caf::unit_t, caf::unit_t, caf::unit_t, caf::unit_t, caf::unit_t, caf::unit_t, caf::unit_t, caf::unit_t, caf::unit_t, caf::unit_t, caf::unit_t, caf::unit_t, caf::unit_t, caf::unit_t, caf::unit_t, caf::unit_t, caf::unit_t, caf::unit_t, caf::unit_t, caf::unit_t, caf::unit_t, caf::unit_t, caf::unit_t, caf::unit_t, caf::unit_t, caf::unit_t>::<unnamed>))’ may be used uninitialized [-Wmaybe-uninitialized]
  106 |     set(std::forward<T>(x));
      |     ~~~^~~~~~~~~~~~~~~~~~~~
In file included from /home/christian/devel/zeek/zeek/auxil/broker/caf/libcaf_core/caf/detail/parser/read_config.hpp:14,
                 from /home/christian/devel/zeek/zeek/auxil/broker/caf/libcaf_core/src/detail/parse.cpp:11:
/home/christian/devel/zeek/zeek/auxil/broker/caf/libcaf_core/caf/detail/parser/read_number_or_timespan.hpp: In function ‘void caf::detail::parser::read_config_value(State&, Consumer&&, InsideList) [with State = caf::parser_state<const char*>; Consumer = caf::detail::config_consumer&; InsideList = std::integral_constant<bool, false>]’:
/home/christian/devel/zeek/zeek/auxil/broker/caf/libcaf_core/caf/detail/parser/read_number_or_timespan.hpp:57:20: note: ‘ic’ declared here
   57 |   interim_consumer ic;
      |                    ^~
```

**Comment by Neverlord** [comment]
@ckreibich did you pass any additional flags to the build? I've compiled CAF (debug build) on Fedora 34 (says `The CXX compiler identification is GNU 11.1.1`) and GCC did complain about `mismatched-new-delete` (I've that fixed in the branch `issue/1280`), but I haven't seen this particular warning. Even when building Broker (current `master`) with the bundled CAF (0.18.3), I don't see this warning. Or are you maybe using an older version of Broker/CAF?

FWIW, these are the warning that I see when building Broker (current `master` branch):

```
# grep warning build-log.txt | sort -u
../../3rdparty/sqlite3.c:114978:3: warning: this ‘if’ clause does not guard... [-Wmisleading-indentation]
../../3rdparty/sqlite3.c:150288:5: warning: this ‘if’ clause does not guard... [-Wmisleading-indentation]
../../caf/libcaf_core/caf/actor_storage.hpp:30:5: warning: ‘void operator delete(void*, void*)’ called on pointer returned from a mismatched allocation function [-Wmismatched-new-delete]
```

**Comment by ckreibich** [comment]
I should have included a pointer to our Zeek CI builds, Dominik — you can see it [here](https://cirrus-ci.com/task/5393599387926528?logs=build#L674). So perhaps it's something in the way Broker builds CAF?

**Comment by Neverlord** [comment]
Seems like the warning has been fixed in the meantime already. 🙂

When updating the submodules to current Broker/CAF (and passing the same options as the CI build), I get:

```
# grep warning build-log.txt | sort -u 
sed: -e expression #1, char 22: unterminated `s' command
[root@cca77bc12491 zeek]# grep warning build-log.txt | sort -u | sed 's/\/mnt\/corelight\///g'
zeek/auxil/broker/3rdparty/sqlite3.c:114978:3: warning: this ‘if’ clause does not guard... [-Wmisleading-indentation]
zeek/auxil/broker/3rdparty/sqlite3.c:150288:5: warning: this ‘if’ clause does not guard... [-Wmisleading-indentation]
zeek/auxil/zeek-aux/rst/rst.c:135:24: warning: ‘addl_pseudo’ is used uninitialized [-Wuninitialized]
zeek/src/patricia.c:295:20: warning: array subscript ‘prefix_t {aka struct _prefix_t}[0]’ is partly outside array bounds of ‘unsigned char[12]’ [-Warray-bounds]
zeek/src/patricia.c:296:20: warning: array subscript ‘prefix_t {aka struct _prefix_t}[0]’ is partly outside array bounds of ‘unsigned char[12]’ [-Warray-bounds]
zeek/src/patricia.c:297:23: warning: array subscript ‘prefix_t {aka struct _prefix_t}[0]’ is partly outside array bounds of ‘unsigned char[12]’ [-Warray-bounds]
zeek/src/patricia.c:299:26: warning: array subscript ‘prefix_t {aka struct _prefix_t}[0]’ is partly outside array bounds of ‘unsigned char[12]’ [-Warray-bounds]
zeek/src/util.cc:2192:38: warning: ‘mallinfo mallinfo()’ is deprecated [-Wdeprecated-declarations]
```

**Comment by ckreibich** [comment]
Cool. :-)

**Comment by ckreibich** [comment]
@Neverlord sorry to resurrect this, but I still see these warnings in recent builds, for example [here](https://cirrus-ci.com/task/6348386589736960?logs=build#L621).

I tried to reproduce this with CAF builds and see the warnings when I switch the build type to match the one we have in Zeek by default: `./configure --build-type=RelWithDebInfo` — specifically, it seems to be `-02` that brings them out:

```
[  1%] Building CXX object libcaf_core/CMakeFiles/libcaf_core_obj.dir/src/config_value.cpp.o
In file included from /home/christian/t1/actor-framework/libcaf_core/src/config_value.cpp:5:
In constructor ‘caf::config_value::config_value(T&&) [with T = long int&; E = void]’,
    inlined from ‘void caf::detail::config_value_consumer::value(T&&) [with T = long int&]’ at /home/christian/t1/actor-framework/libcaf_core/caf/detail/config_consumer.hpp:135:12,
    inlined from ‘void caf::detail::parser::read_number_or_timespan(State&, Consumer&, EnableRange)::interim_consumer::value(int64_t) [with State = caf::parser_state<const char*>; Consumer = caf::detail::config_value_consumer; EnableRange = std::integral_constant<bool, false>]’ at /home/christian/t1/actor-framework/libcaf_core/caf/detail/parser/read_number_or_timespan.hpp:46:23,
    inlined from ‘caf::detail::parser::read_number<caf::parser_state<const char*>, caf::detail::parser::read_number_or_timespan<caf::parser_state<const char*>, caf::detail::config_value_consumer, std::integral_constant<bool, false> >(caf::parser_state<const char*>&, caf::detail::config_value_consumer&, std::integral_constant<bool, false>)::interim_consumer, std::integral_constant<bool, true>, std::integral_constant<bool, false> >(caf::parser_state<const char*>&, caf::detail::parser::read_number_or_timespan<caf::parser_state<const char*>, caf::detail::config_value_consumer, std::integral_constant<bool, false> >(caf::parser_state<const char*>&, caf::detail::config_value_consumer&, std::integral_constant<bool, false>)::interim_consumer&, std::integral_constant<bool, true>, std::integral_constant<bool, false>)::<lambda()>’ at /home/christian/t1/actor-framework/libcaf_core/caf/detail/parser/read_number.hpp:51:21,
    inlined from ‘caf::detail::parser::read_number<caf::parser_state<const char*>, caf::detail::parser::read_number_or_timespan<caf::parser_state<const char*>, caf::detail::config_value_consumer, std::integral_constant<bool, false> >(caf::parser_state<const char*>&, caf::detail::config_value_consumer&, std::integral_constant<bool, false>)::interim_consumer, std::integral_constant<bool, true>, std::integral_constant<bool, false> >(caf::parser_state<const char*>&, caf::detail::parser::read_number_or_timespan<caf::parser_state<const char*>, caf::detail::config_value_consumer, std::integral_constant<bool, false> >(caf::parser_state<const char*>&, caf::detail::config_value_consumer&, std::integral_constant<bool, false>)::interim_consumer&, std::integral_constant<bool, true>, std::integral_constant<bool, false>)::<lambda()>’ at /home/christian/t1/actor-framework/libcaf_core/caf/detail/parser/read_number.hpp:49:42,
    inlined from ‘caf::detail::scope_guard<Fun>::~scope_guard() [with Fun = caf::detail::parser::read_number<caf::parser_state<const char*>, caf::detail::parser::read_number_or_timespan<caf::parser_state<const char*>, caf::detail::config_value_consumer, std::integral_constant<bool, false> >(caf::parser_state<const char*>&, caf::detail::config_value_consumer&, std::integral_constant<bool, false>)::interim_consumer, std::integral_constant<bool, true>, std::integral_constant<bool, false> >(caf::parser_state<const char*>&, caf::detail::parser::read_number_or_timespan<caf::parser_state<const char*>, caf::detail::config_value_consumer, std::integral_constant<bool, false> >(caf::parser_state<const char*>&, caf::detail::config_value_consumer&, std::integral_constant<bool, false>)::interim_consumer&, std::integral_constant<bool, true>, std::integral_constant<bool, false>)::<lambda()>]’ at /home/christian/t1/actor-framework/libcaf_core/caf/detail/scope_guard.hpp:29:11,
    inlined from ‘void caf::detail::parser::read_number(State&, Consumer&, EnableFloat, EnableRange) [with State = caf::parser_state<const char*>; Consumer = caf::detail::parser::read_number_or_timespan<caf::parser_state<const char*>, caf::detail::config_value_consumer, std::integral_constant<bool, false> >(caf::parser_state<const char*>&, caf::detail::config_value_consumer&, std::integral_constant<bool, false>)::interim_consumer; EnableFloat = std::integral_constant<bool, true>; EnableRange = std::integral_constant<bool, false>]’ at /home/christian/t1/actor-framework/libcaf_core/caf/detail/parser/read_number.hpp:178:1,
    inlined from ‘void caf::detail::parser::read_number_or_timespan(State&, Consumer&, EnableRange) [with State = caf::parser_state<const char*>; Consumer = caf::detail::config_value_consumer; EnableRange = std::integral_constant<bool, false>]’ at /home/christian/t1/actor-framework/libcaf_core/caf/detail/parser/read_number_or_timespan.hpp:74:5,
    inlined from ‘void caf::detail::parser::read_config_value(State&, Consumer&&, InsideList) [with State = caf::parser_state<const char*>; Consumer = caf::detail::config_value_consumer&; InsideList = std::integral_constant<bool, false>]’ at /home/christian/t1/actor-framework/libcaf_core/caf/detail/parser/read_config.hpp:228:5,
    inlined from ‘static caf::expected<caf::config_value> caf::config_value::parse(caf::string_view::iterator, caf::string_view::iterator)’ at /home/christian/t1/actor-framework/libcaf_core/src/config_value.cpp:79:28:
/home/christian/t1/actor-framework/libcaf_core/caf/config_value.hpp:106:8: warning: ‘*(long int*)((char*)&ic + offsetof(caf::detail::parser::read_number_or_timespan::interim_consumer, caf::detail::parser::read_number_or_timespan::interim_consumer::interim.caf::variant<caf::none_t, long int, double>::data_.caf::detail::variant_data<caf::none_t, long int, double, caf::unit_t, caf::unit_t, caf::unit_t, caf::unit_t, caf::unit_t, caf::unit_t, caf::unit_t, caf::unit_t, caf::unit_t, caf::unit_t, caf::unit_t, caf::unit_t, caf::unit_t, caf::unit_t, caf::unit_t, caf::unit_t, caf::unit_t, caf::unit_t, caf::unit_t, caf::unit_t, caf::unit_t, caf::unit_t, caf::unit_t, caf::unit_t, caf::unit_t, caf::unit_t, caf::unit_t>::<unnamed>))’ may be used uninitialized [-Wmaybe-uninitialized]
  106 |     set(std::forward<T>(x));
      |     ~~~^~~~~~~~~~~~~~~~~~~~
In file included from /home/christian/t1/actor-framework/libcaf_core/caf/detail/parser/read_config.hpp:14,
                 from /home/christian/t1/actor-framework/libcaf_core/src/config_value.cpp:16:
/home/christian/t1/actor-framework/libcaf_core/caf/detail/parser/read_number_or_timespan.hpp: In static member function ‘static caf::expected<caf::config_value> caf::config_value::parse(caf::string_view::iterator, caf::string_view::iterator)’:
/home/christian/t1/actor-framework/libcaf_core/caf/detail/parser/read_number_or_timespan.hpp:57:20: note: ‘ic’ declared here
   57 |   interim_consumer ic;
      |                    ^~
```

**Comment by Neverlord** [comment]
Confirmed, `RelWithDebInfo` reproduces the warnings.

**Comment by Neverlord** [comment]
To check whether it's still showing up, I ran GCC 11 on macOS today. I didn't see that warning, but similar warnings that look like false positives at a first glance:

```
[174/596] Building CXX object libcaf_core/CMakeFiles/caf-core-test.dir/test/async/blocking_consumer.cpp.o
In file included from /Users/neverlord/workspace/project/caf/libcaf_core/test/async/blocking_consumer.cpp:7:
/Users/neverlord/workspace/project/caf/libcaf_core/caf/async/blocking_consumer.hpp: In member function 'caf::error caf::async::blocking_consumer<T>::abort_reason() const':
/Users/neverlord/workspace/project/caf/libcaf_core/caf/async/blocking_consumer.hpp:183:3: warning: no return statement in function returning non-void [-Wreturn-type]
  183 |   }
      |   ^
[543/596] Building CXX object examples/CMakeFiles/observe-on.dir/flow/observe-on.cpp.o
In file included from /Users/neverlord/workspace/project/caf/libcaf_core/caf/intrusive_cow_ptr.hpp:10,
                 from /Users/neverlord/workspace/project/caf/libcaf_core/caf/message.hpp:17,
                 from /Users/neverlord/workspace/project/caf/libcaf_core/caf/error.hpp:16,
                 from /Users/neverlord/workspace/project/caf/libcaf_core/caf/message_id.hpp:14,
                 from /Users/neverlord/workspace/project/caf/libcaf_core/caf/abstract_channel.hpp:11,
                 from /Users/neverlord/workspace/project/caf/libcaf_core/caf/abstract_actor.hpp:16,
                 from /Users/neverlord/workspace/project/caf/libcaf_core/caf/actor_system.hpp:18,
                 from /Users/neverlord/workspace/project/caf/examples/flow/observe-on.cpp:3:
In member function 'T* caf::intrusive_ptr< <template-parameter-1-1> >::get() const [with T = caf::actor_control_block]',
    inlined from 'caf::actor_control_block* caf::actor::get() const' at /Users/neverlord/workspace/project/caf/libcaf_core/caf/actor.hpp:148:20,
    inlined from 'To* caf::actor_cast_access<To*, From, 0>::operator()(const T&) const [with T = caf::actor; <template-parameter-2-2> = void; To = caf::abstract_actor; From = caf::actor]' at /Users/neverlord/workspace/project/caf/libcaf_core/caf/actor_cast.hpp:94:19,
    inlined from 'T caf::actor_cast(U&&) [with T = caf::abstract_actor*; U = const caf::actor&]' at /Users/neverlord/workspace/project/caf/libcaf_core/caf/actor_cast.hpp:161:11,
    inlined from 'caf::actor_system::spawn_inactive<caf::event_based_actor>()::<lambda()>' at /Users/neverlord/workspace/project/caf/libcaf_core/caf/actor_system.hpp:675:53,
    inlined from 'caf::actor_system::launcher<F>::~launcher() [with F = caf::actor_system::spawn_inactive<caf::event_based_actor>()::<lambda()>]' at /Users/neverlord/workspace/project/caf/libcaf_core/caf/actor_system.hpp:630:11,
    inlined from 'std::_Head_base<1, caf::actor_system::launcher<caf::actor_system::spawn_inactive<caf::event_based_actor>()::<lambda()> >, false>::~_Head_base()' at /usr/local/Cellar/gcc@11/11.3.0/include/c++/11/tuple:187:12,
    inlined from 'std::_Tuple_impl<1, caf::actor_system::launcher<caf::actor_system::spawn_inactive<caf::event_based_actor>()::<lambda()> > >::~_Tuple_impl()' at /usr/local/Cellar/gcc@11/11.3.0/include/c++/11/tuple:416:12,
    inlined from 'std::_Tuple_impl<0, caf::event_based_actor*, caf::actor_system::launcher<caf::actor_system::spawn_inactive<caf::event_based_actor>()::<lambda()> > >::~_Tuple_impl()' at /usr/local/Cellar/gcc@11/11.3.0/include/c++/11/tuple:258:12,
    inlined from 'std::tuple<caf::event_based_actor*, caf::actor_system::launcher<caf::actor_system::spawn_inactive<caf::event_based_actor>()::<lambda()> > >::~tuple()' at /usr/local/Cellar/gcc@11/11.3.0/include/c++/11/tuple:985:11,
    inlined from 'void {anonymous}::caf_main(caf::actor_system&, const {anonymous}::config&)' at /Users/neverlord/workspace/project/caf/examples/flow/observe-on.cpp:45:1:
/Users/neverlord/workspace/project/caf/libcaf_core/caf/intrusive_ptr.hpp:146:12: warning: '*(const caf::intrusive_ptr<caf::actor_control_block>*)((char*)&<unnamed> + offsetof(std::tuple<caf::event_based_actor*, caf::actor_system::launcher<caf::actor_system::spawn_inactive::._anon_253> >,std::tuple<caf::event_based_actor*, caf::actor_system::launcher<caf::actor_system::spawn_inactive::._anon_253> >::<unnamed>.std::_Tuple_impl<0, caf::event_based_actor*, caf::actor_system::launcher<caf::actor_system::spawn_inactive::._anon_253> >::<unnamed>.std::_Tuple_impl<1, caf::actor_system::launcher<caf::actor_system::spawn_inactive::._anon_253> >::<unnamed>.std::_Head_base<1, caf::actor_system::launcher<caf::actor_system::spawn_inactive::._anon_253>, false>::_M_head_impl.caf::actor_system::launcher<caf::actor_system::spawn_inactive::._anon_253>::<unnamed>)).caf::intrusive_ptr<caf::actor_control_block>::ptr_' may be used uninitialized [-Wmaybe-uninitialized]
  146 |     return ptr_;
      |            ^~~~
/Users/neverlord/workspace/project/caf/examples/flow/observe-on.cpp: In function 'void {anonymous}::caf_main(caf::actor_system&, const {anonymous}::config&)':
/Users/neverlord/workspace/project/caf/examples/flow/observe-on.cpp:26:8: note: '<structured bindings>' declared here
   26 |   auto [snk, launch_snk] = sys.spawn_inactive<actor_t>();
      |        ^~~~~~~~~~~~~~~~~
In file included from /Users/neverlord/workspace/project/caf/examples/flow/observe-on.cpp:3:
In lambda function,
    inlined from 'caf::actor_system::launcher<F>::~launcher() [with F = caf::actor_system::spawn_inactive<caf::event_based_actor>()::<lambda()>]' at /Users/neverlord/workspace/project/caf/libcaf_core/caf/actor_system.hpp:630:11,
    inlined from 'std::_Head_base<1, caf::actor_system::launcher<caf::actor_system::spawn_inactive<caf::event_based_actor>()::<lambda()> >, false>::~_Head_base()' at /usr/local/Cellar/gcc@11/11.3.0/include/c++/11/tuple:187:12,
    inlined from 'std::_Tuple_impl<1, caf::actor_system::launcher<caf::actor_system::spawn_inactive<caf::event_based_actor>()::<lambda()> > >::~_Tuple_impl()' at /usr/local/Cellar/gcc@11/11.3.0/include/c++/11/tuple:416:12,
    inlined from 'std::_Tuple_impl<0, caf::event_based_actor*, caf::actor_system::launcher<caf::actor_system::spawn_inactive<caf::event_based_actor>()::<lambda()> > >::~_Tuple_impl()' at /usr/local/Cellar/gcc@11/11.3.0/include/c++/11/tuple:258:12,
    inlined from 'std::tuple<caf::event_based_actor*, caf::actor_system::launcher<caf::actor_system::spawn_inactive<caf::event_based_actor>()::<lambda()> > >::~tuple()' at /usr/local/Cellar/gcc@11/11.3.0/include/c++/11/tuple:985:11,
    inlined from 'void {anonymous}::caf_main(caf::actor_system&, const {anonymous}::config&)' at /Users/neverlord/workspace/project/caf/examples/flow/observe-on.cpp:45:1:
/Users/neverlord/workspace/project/caf/libcaf_core/caf/actor_system.hpp:672:19: warning: '*(const caf::actor_system::spawn_inactive::._anon_253*)((char*)&<unnamed> + offsetof(std::tuple<caf::event_based_actor*, caf::actor_system::launcher<caf::actor_system::spawn_inactive::._anon_253> >,std::tuple<caf::event_based_actor*, caf::actor_system::launcher<caf::actor_system::spawn_inactive::._anon_253> >::<unnamed>.std::_Tuple_impl<0, caf::event_based_actor*, caf::actor_system::launcher<caf::actor_system::spawn_inactive::._anon_253> >::<unnamed>.std::_Tuple_impl<1, caf::actor_system::launcher<caf::actor_system::spawn_inactive::._anon_253> >::<unnamed>.std::_Head_base<1, caf::actor_system::launcher<caf::actor_system::spawn_inactive::._anon_253>, false>::_M_head_impl.caf::actor_system::launcher<caf::actor_system::spawn_inactive::._anon_253>::<unnamed>)).caf::actor_system::spawn_inactive<caf::event_based_actor>()::<lambda()>::__host' may be used uninitialized [-Wmaybe-uninitialized]
  672 |     auto launch = [res, host{cfg.host}] {
      |                   ^~~~~~~~~~~~~~~~~~~~~~~
  673 |       // Note: we pass `res` to this lambda instead of `ptr` to keep a strong
      |       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  674 |       //       reference to the actor.
      |       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  675 |       static_cast<Impl*>(actor_cast<abstract_actor*>(res))
      |       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  676 |         ->launch(host, false, false);
      |         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  677 |     };
      |     ~              
/Users/neverlord/workspace/project/caf/examples/flow/observe-on.cpp: In function 'void {anonymous}::caf_main(caf::actor_system&, const {anonymous}::config&)':
/Users/neverlord/workspace/project/caf/examples/flow/observe-on.cpp:26:8: note: '<structured bindings>' declared here
   26 |   auto [snk, launch_snk] = sys.spawn_inactive<actor_t>();
      |        ^~~~~~~~~~~~~~~~~
[596/596] Linking CXX executable examples/length_prefix_framing/chat-server
```

I'll also double-check with GCC on Fedora again.

**Comment by Neverlord** [comment]
I can no longer reproduce the original warning, but the oldest version for GCC 11 we have in our CI setup seems to be 11.4. If it's a warning that's only raised by 11.1 specifically (and still exists in CAF 1.0), I don't think it'd be worth finding a workaround.
