### ISSUE TITLE
OpenSSL test failure

### ISSUE THREAD

**Issue by josephnoir** [actor-framework/actor-framework#591]
The [openssl authentication test](https://github.com/actor-framework/actor-framework/blob/develop/libcaf_openssl/test/authentication.cpp) fails at times because the ping pong messages are not processed correctly. In a call to `exec_loop()` both calls to `exec_one(...)` may return false even though not all ping pong messages have been passed around. As a result, the ping actor never quits and the test is killed by the watchdog after the timeout.

Adding repeated calls to [`exec_loop()`](https://github.com/actor-framework/actor-framework/blob/develop/libcaf_openssl/test/authentication.cpp#L196) seems to increase the probability that it succeeds. Not a solution, though.

Could also be a network timing problem for the communication between the actors.

**Comment by josephnoir** [comment]
It seems that adding a short sleep in `exec_loop` also addresses the problem:
```
void exec_loop() {
  while (exec_one(client_side) | exec_one(server_side)) {
    std::this_thread::sleep_for(std::chrono::milliseconds(10));
  }
}
```

Guess, that is what we wanted to avoid by using a scheduler that we can advance manually.

**Comment by josephnoir** [comment]
The test `openssl_dynamic_remote_actor` fails as well [in Jenkins](https://jenkins.inet.haw-hamburg.de/job/CAF/job/develop%20branch%20gcc/label_exp=Linux%20&&%20gcc4.8/668/console).

**Comment by Neverlord** [comment]
Fixed in `develop`.

**Comment by MarcinNaw** [comment]
Unfortunately, the test `openssl_dynamic_remote_actor` still fails on my Debian 9.2 with gcc version 6.3.0 20170516 (Debian 6.3.0-18):

```
      Start 61: openssl_authentication
61/62 Test #61: openssl_authentication ...........   Passed    0.05 sec
      Start 62: openssl_dynamic_remote_actor
62/62 Test #62: openssl_dynamic_remote_actor .....***Exception: Other  0.02 sec

98% tests passed, 1 tests failed out of 62

Total Test time (real) =   2.24 sec

The following tests FAILED:
	 62 - openssl_dynamic_remote_actor (OTHER_FAULT)
Errors while running CTest
```

My installation routine is as follows:

```
# OPENSSL DEV INSTALL
cd ${DIR_GIT}
git clone https://github.com/openssl/openssl.git
cd "openssl"
./config --prefix="${DIR_INSTALL}openssl" --openssldir="${DIR_INSTALL}.opensslconf"
make -j ${N_CPU}
make test
make install

# CAF INSTALL
cd ${DIR_GIT}
git clone https://github.com/actor-framework/actor-framework.git
cd "actor-framework"
git checkout develop
./configure --prefix="${DIR_INSTALL}caf" --with-openssl="${DIR_INSTALL}openssl" --with-log-level=DEBUG
make -j ${N_CPU}
make test # <-- fails
make install
```

Can someone confirm my observations?

**Comment by josephnoir** [comment]
What OpenSSL version are you using?

I think there were API changes with the 1.1.X releases and the authentication used in the `openssl_dynamic_remote_actor` test might not work anymore.

**Comment by MarcinNaw** [comment]
I am using the master branch on github, so this should be a 1.1.X release. Which [branch](https://github.com/openssl/openssl/branches) do you guys recommend?

**Comment by josephnoir** [comment]
On my system, I have the following OpenSSL version (via macOS homebrew):
```
$ /usr/local/opt/openssl/bin/openssl version
OpenSSL 1.0.2l  25 May 2017
```
This is by no means a recommendation on crypto stuff. It is more a comment, that even though the test does not work with openssl 1.1.X, you can try to use VAST with the same version as this might just be a configuration thing. The `openssl_authentication` test works, for example.
